### DISCUSSION TITLE
Add Formatters to ServiceClaim

### DISCUSSION THREAD

**Discussion by filariow** [primaza/primaza#200] [Ideas]
The following is a proposal for adding Formatters to ServiceClaim.
This new feature will allow Developers to define the format they want for projected Service data.
> :eyes: Please take a look at [https://github.com/filariow/primaza/commit/d79b9ba023d738eb39640bad9e3ded2348699864](https://github.com/filariow/primaza/commit/d79b9ba023d738eb39640bad9e3ded2348699864) for an implementation of the API changes described in this discussion.

The ServiceClaim will have a new `spec`'s section named `formatters`, defined as shown in the following example:

```yaml
apiVersion: primaza.io/v1alpha1
kind: ServiceClaim
spec:
  # ...
  formatters:
    JSONFormatter:
      filepath: /path/to/folder
      filename: myconfig.json
      rootPath: /path/to/json/property # default: /
      mapper:
        configuration:
          strategy: IncludeMissing   # or ExcludeMissing
          missingFieldsRoot: /data/others  # JSONPath
          mappings:
          - field: ServiceEndpointDefinitionField
            path: /data/myservice/SEDFieldName  # JSONPath
    GoTemplateFormatter:
      filepath: /path/to/folder
      filename: myconfig.myextension
      mapper:
        configuration:
          template: |
            {{ range .Data }}
              {{ .Key }}:{{ .Value }}
            {{ end }}          
```

The above specification will project a JSON file `/path/to/folder/myconfig.json`.
The file will look like the following:
```json
{
  "data": {
    "myservice": {
      "SEDFieldName": "I'm the value from ServiceEndpointDefinitionField"
    },
    "others": {
      "SEDFieldName2": "I'm the value from a non mapped ServiceEndpointDefinitionField"
    }
  }
}
```
The section `/data/others` will be present only if the mapper's `strategy` is `IncludeMissing`.

Also a file `/path/to/folder/myconfig.myextension` is projected.
It's content will be a newline separated list of all Secret's data in the format `key:value`, like follows:
```
SEDFieldName:I'm the value from ServiceEndpointDefinitionField
SEDFieldName2:I'm the value from a non mapped ServiceEndpointDefinitionField
```

**Comment by dperaza4dustbit** [comment]
Is the mapper required here? We know exactly what fields are going to be projected via volume mount in the absent of formatter I think the only required fields are path, format and file name. I only see the need of the mapper when specifying a go template format. Also, can you explain a bit more what you had in mind when thinking about strategies Include and Exclude missing?

**Comment by filariow** [comment]
Mappers are thought to provide the user the possibility to generate a complex configuration file. If we take the example of a C#'s JSON appsettings, mappers can help the developer to be compliant with complex structures that are often used (cfr. https://www.brainstormcreative.co.uk/c/how-to-read-values-from-appsettings-json-file-in-net-core-6/).

I'd say that an initial implementation of this feature may avoid mappers, but we should take this in mind to provide developers complete flexibility in defining their configurations.
So, initially the JSONFormatter may be as simple as the following:
```yaml
  formatters:
    JSONFormatter:
      filepath: /path/to/folder
      filename: myconfig.json
```

The idea behind `IncludeMissing` and `ExcludeMissing` strategies is the following: should I project a key if you don't define a mapper for it? If the `strategy` is `ExcludeMissing` it won't be projected; if the `strategy` is `IncludeMissing` the mapper-missing key will be projected at `missingFieldsRoot/KEY`. To avoid complex validation on `missingFieldsRoot` (required field if strategy is `IncludeMissing` we can have a default value for it, like `others`)

**Comment by filariow** [comment]
Consider the following use case:
```
An user would like to claim a Service and project its Service Endpoint Definition secret as files in a folder (Volume and VolumeMount). Together with the keys found in the secret they'd like to project a composite one.
```

To clarify consider this example. The Service Endpoint Definition contains `host: my-service` and `port: 1234`. The user would like to have the composite field `url: https://my-service:1234`.

To cover this scenario we may introduce the following Formatter:
```yaml
spec:
  formatter:
    volumeMountFormatter:                                         # or serviceBindingFormatter
      compositeKeys:
      - name: "url"
        template: "https://{{.url}}:{{.port}}"
```

The Service Endpoint Definition secret generated by the ServiceClaim controller would be similar to the following:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-service
  namespace: application-namespace
stringData:
  host: my-service
  port: 1234
  url: https://my-service:1234
```

If no formatter is specified in the `formatter` field, Primaza assumes the formatter is an empty `volumeMountFormatter`.

As a side effect of this implementation, it would be possible to add values directly from the service claim. Consider the following specification:

```yaml
spec:
  formatter:
    volumeMountFormatter:                                         # or serviceBindingFormatter
      compositeKeys:
      - name: "the-primaza-book"
        template: "https://primaza.io"
```

In future, we can extend this formatter to implement allowlist and denylist for Service Endpoint Definition (SED) secrets, to restrict the number of SED secret fields projected
