### ISSUE TITLE
Implement Formatter Idea for Json and Yaml Formats

### ISSUE THREAD

**Issue by filariow** [primaza/primaza#273]
# Story

As a Primaza user,
I will like to be able to determine how my data gets projected into application
so that I can consume SEDs in the format that my application already understands.

## Background

Today Primaza only support projection of SEDs into the application via volume mount of a secret where each field of the secret becomes a file where name of file is the key and the content of the file is value.
This approach is fine if application support Service Binding specification.
However if we want to support more projection methods that better match what applications expects we should support at least JSON and YAML file formats for the SED key/value list. 

## Glossary

Formatter: A mechanism to format SEDs in different formats.

## Out of scope

* Go Template Format
* JSON/YAML Mappers

## In Scope

* JSON format
* YAML format

## **Approach**(Required)

Instead of sending an SED represented as a secret that gets mounted resulting of multiple files per key, we can send a secret with a single key being the file name and the value being a base64 encoded blob with the specified format containing key/value list for the SED.
The mounting will happen exactly as it happens now but the result inside the container will be a single file instead of multiple files. 

## Demo requirements

A great demo will be showing a service claim showing JSON format and another claim showing YAML format.
The Service Binding projection should still work as before.

## Acceptance Criteria

* Development
:question: Formatter support Json and Yaml in addition to Service Binding
* QE
:question: New test for Json format
:question: New test for Yaml format
* Documentation
:question: Documentation on how to add formatter section in claim CR 

### Legend

:question: Unknown
:heavy_check_mark: Verified
:x: Unsatisfied

### Discussed in https://github.com/primaza/primaza/discussions/200

<div type='discussions-op-text'>

<sup>Originally posted by **filariow** June  7, 2023</sup>
The following is a proposal for adding Formatters to ServiceClaim.
This new feature will allow Developers to define the format they want for projected Service data.
> :eyes: Please take a look at [https://github.com/filariow/primaza/commit/d79b9ba023d738eb39640bad9e3ded2348699864](https://github.com/filariow/primaza/commit/d79b9ba023d738eb39640bad9e3ded2348699864) for an implementation of the API changes described in this discussion.

The ServiceClaim will have a new `spec`'s section named `formatters`, defined as shown in the following example:

```yaml
apiVersion: primaza.io/v1alpha1
kind: ServiceClaim
spec:
  # ...
  formatters:
    JSONFormatter:
      filepath: /path/to/folder
      filename: myconfig.json
      rootPath: /path/to/json/property # default: /
      mapper:
        configuration:
          strategy: IncludeMissing   # or ExcludeMissing
          missingFieldsRoot: /data/others  # JSONPath
          mappings:
          - field: ServiceEndpointDefinitionField
            path: /data/myservice/SEDFieldName  # JSONPath
    GoTemplateFormatter:
      filepath: /path/to/folder
      filename: myconfig.myextension
      mapper:
        configuration:
          template: |
            {{ range .Data }}
              {{ .Key }}:{{ .Value }}
            {{ end }}          
```

The above specification will project a JSON file `/path/to/folder/myconfig.json`.
The file will look like the following:
```json
{
  "data": {
    "myservice": {
      "SEDFieldName": "I'm the value from ServiceEndpointDefinitionField"
    },
    "others": {
      "SEDFieldName2": "I'm the value from a non mapped ServiceEndpointDefinitionField"
    }
  }
}
```
The section `/data/others` will be present only if the mapper's `strategy` is `IncludeMissing`.

Also a file `/path/to/folder/myconfig.myextension` is projected.
It's content will be a newline separated list of all Secret's data in the format `key:value`, like follows:
```
SEDFieldName:I'm the value from ServiceEndpointDefinitionField
SEDFieldName2:I'm the value from a non mapped ServiceEndpointDefinitionField
```</div>
