### ISSUE TITLE
Support multiple targets

### ISSUE THREAD

**Issue by filariow** [primaza/primaza#274]
# Story

As a GitOps User,
I would like to configure how Primaza delivers the Service Endpoint Definition Secret
so that I define my custom mounting and/or have the mounting versioned in Git

## Background

As a reaction to ServiceClaims creation, one or more ServiceBindings and Secrets (Service Endpoint Definition (SED)) are created.
This means the RegisteredService binding data are projected in a secret (SED), pushed to the workload namespace, and the workload is tampered to mount this secret.

In some scenarios, it is preferred to have this data delivered differently.
One example is when the user needs a custom secret mounting configuration or they would like to have the mounting versioned in Git.

## Glossary

See glossary in architecture document

## Out of scope

NA

## In Scope

* ServiceClaim's `target` spec

## Approach

We can modify the ServiceClaim introducing a parent and some siblings for the field `application`.
Also we can rename the `application` field to `workload`.
The first sibling to implement is `secret`.
It will just contain a `name` field that specifies the name of the secret that the Primaza will push into the application namespace.

As a result, the updated ServiceClaim Specification would resemble the following examples:

```yaml
apiVersion: primaza.io/v1alpha1
kind: ServiceClaim
metadata:
  name: sc-test
spec:
  serviceClassIdentity: [ ... ]
  serviceEndpointDefinitionKeys: [ ... ]
  applicationClusterContext:
    # ...
  target:
    application:
      kind: Deployment
      apiVersion: apps/v1
      name: stage-app
```

and

```yaml
apiVersion: primaza.io/v1alpha1
kind: ServiceClaim
metadata:
  name: sc-test
spec:
# ...
  target:
    secret:
      name: mysecret
```

To simplify, `application` and `secret` can be implemented as mutually exclusive for now.
In future we may extend this mechanism and implement new siblings, like `vault`, `custom`, etc.

## Demo requirements

A great demo will show an application deployed through ArgoCD.
The application has specific need for mounting the data, so the ServiceClaim is using the `spec.target.secret` field to project the data.
The mounting is declared in the application's Deployment specification.

## Acceptance Criteria

* Development
:question: If `spec.target.secret` is defined, the ControlPlane's ServiceClaim controller is pushing just the secret to application namespaces

 * QE
:question: There are test cases for secret pushing

 * Docs
:question: There is a section in our ServiceClaim docs dedicated to explaining how to push just the secret and how to bind the workloads

### Legend

:question: Unknown
:heavy_check_mark: Verified
:x: Unsatisfied
