### ISSUE TITLE
RegisteredService Healthchecks' required failures

### ISSUE THREAD

**Issue by filariow** [primaza/primaza#291]
# Story

As a Primaza Administrator,
I would like unhealthy Services to be reported
so that I can report a problem and, when it's possible, bind to new Services

## Background

RegisteredServices can be configured to be monitored via health checks.

```mermaid
flowchart TD
    subgraph healthcheck[Healthcheck Running]
        Running((Healthcheck\nrunning))
        Crashed{Healthcheck\nCrashed?}
        Failed{Healthcheck\nFailed?}
        IsClaimed{Is\nRegistered\nService\nClaimed?}
        Unknown
        Available
        Unreachable

        Running --> Crashed
        Crashed -->|Yes| Unknown
        Crashed -->|No| Failed
        Failed -->|Yes| Unreachable
        Failed -->|No| IsClaimed
        IsClaimed -->|Yes| Claimed
        IsClaimed -->|No| Available
    end
    subgraph regsvc_create[Registered Service Creation]
        Start((Registered\nService\n is created))
        cAvailable[Available]
        cUnknown[Unknown]
        HealthcheckDefined{Is Healthcheck\ndefined?}

        Start --> HealthcheckDefined
        HealthcheckDefined -->|No| cAvailable
        HealthcheckDefined -->|Yes| cUnknown
    end
````

An health check failure will move the RegisteredService to `Unreachable`.
However, the failure may be transient, and should be retried before changing the RegisteredService's state.

We need a way of configuring how many times Primaza the health check should fail before updating the state.

## Glossary

See glossary in architecture document

## Out of scope

NA

## In Scope

* RegisteredService's state update with failing health checks

## Approach

Here you find an example of a RegisteredService with health check configured.

```yaml
apiVersion: primaza.io/v1alpha1
kind: RegisteredService
metadata:
  name: my-registeredservice
  namespace: primaza-system
spec:
  healthcheck:
    container:
      image: "alpine:latest"
      command:
      - /bin/sh
      - -c
      - sleep 1 && exit 0
      minutes: 1
  serviceClassIdentity:
    - name: type
      value: psqlserver
  serviceEndpointDefinition:
    - name: port
      value: "5432"
```

We can introduce the new field `requiredFailures` in the `healthcheck` property.
It represents the number of subsequent failures required before the registered service can be considered `Unreachable`.

When an health checks <span style="color:red">fails</span>, we take track in the RegisteredService status, in the field `.status.healthcheck.latestFailures` and in its `.status.conditions`.
This field is a list of entries respecting the following spec:
```yaml
time: ISO 8601 formatted datetime
reason: description of the failure
```
The data contained in the field `.status.healthcheck.latestFailures` is also used to build a condition that is added to the `.status.conditions` list.

When the `.status.healthcheck.latestFailures` contains a number of failures greater than the `spec.healthcheck.requiredFailures`, the status is updated to `Unreachable`.

When an health check <span style="color:green">passes</span>, the `.status.healthcheck.latestFailures` list is emptied.

## Demo requirements

NA

## Dependencies

NA

## Acceptance Criteria

* Development
:question: RegisteredService API has the fields `.spec.healthcheck.requiredFailures` and `.status.healthcheck.latestFailures`
:question: RegisteredService healthchecks updates the `.status.healthcheck.latestFailures` field
:question: RegisteredService controller updates the `.status.state` and `.status.conditions` with respect to `.status.healthcheck.latestFailures` and `.spec.healthcheck.requiredFailures` fields

 * QE
:question: Test cases are updated with `.spec.healthcheck.requiredFailures`

 * Docs
:question: There is a section in RegisteredService's docs dedicated to explaining healthchecks

### Legend

:question: Unknown
:heavy_check_mark: Verified
:x: Unsatisfied
